default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: TriviaCompass_development
  host: localhost
  username: trivia_user
  password: password

test:
  <<: *default
  database: TriviaCompass_test
  host: localhost
  username: trivia_user
  password: password


production:
  <<: *default
  database: TriviaCompass
  host:  <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
