default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: trivia_development
  host: localhost

test:
  <<: *default
  database: trivia_test
  host: localhost

production:
  <<: *default
  database: TriviaCompass
  host:  <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
