# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21da7bd0e7d39ed7169ff6a2c01355b35e4bb2eb4a4598b1beabd3329865439ebd85f6fbfcfb66f550de4129a483ce980c74f4875a3693aeaf8576b329a78407

test:
  secret_key_base: ab028adde34f9554402b736ad4e52cb8ca3c5dcef8d0985b1620f581edc40b8c26c3fdf672c41f92b8612e13d6488f626d72047a62d2e745da736a6daa14be57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
